---
- name: USE dellemc.openmanage.redfish_powerstate TO POWER UP THE POWEREDGE SERVER
  hosts: idrac
  connection: local
  gather_facts: false
  vars:
    powerstate: "On"

  tasks:
  - name: "Manage power state of a specified device"
    dellemc.openmanage.redfish_powerstate:
      baseuri: "{{ idrac_ip }}"
      username: "root"
      password: "{{ idrac_password }}"
      #ca_path: "/path/to/ca_cert.pem"
      validate_certs: False
      reset_type: "{{ powerstate }}"
      #resource_id: "System.Embedded.1"
