---
- name: THIS PLAYBOOK WILL IMPORT AND USE PRECHECK TASKS
  hosts: redfish_apis
  connection: local
  gather_facts: false

  tasks:
  # When connecting to a redfish interface dont use gather_facts
  # community.general.redfish_info is a possible replacement
  - name: Get default inventory information
    community.general.redfish_info:
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: results

  - name:
    import_tasks:
      prechecks-redfish.yml
